### ISSUE TITLE
Can not use visualization after update keras

### ISSUE THREAD

**Issue by pengpaiSH** [fchollet/hualos#2]
I have tried such amazing visualization tool when it was born month ago and it worked well. After I update keras (git pull) recently. The same code run into error after one epoch.

```
Traceback (most recent call last):
  File "keras_mnist.py", line 93, in <module>
    cnn = model.fit(X_train, Y_train, validation_data = (X_valid, Y_valid), batch_size = batch_size, show_accuracy = show_accuracy, callbacks=[history, checkpointer, remote], nb_epoch = nb_epoch)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 465, in fit
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 228, in _fit
  File "build/bdist.linux-x86_64/egg/keras/callbacks.py", line 39, in on_epoch_end
  File "build/bdist.linux-x86_64/egg/keras/callbacks.py", line 258, in on_epoch_end
AttributeError: 'RemoteMonitor' object has no attribute 'logs'
```

@fchollet What shall I do?

**Comment by fchollet** [comment]
This should fix it: https://github.com/fchollet/keras/commit/1e3d9f7be11410a0eaf071b3ca68d4ca7bfad86b

You can try again now.

**Comment by pengpaiSH** [comment]
@fchollet After I have updated keras, now the error becomes:

```
Traceback (most recent call last):
  File "keras_mnist.py", line 93, in <module>
    cnn = model.fit(X_train, Y_train, validation_data = (X_valid, Y_valid), batch_size = batch_size, show_accuracy = show_accuracy, callbacks=[history, checkpointer, remote], nb_epoch = nb_epoch)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 465, in fit
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 228, in _fit
  File "build/bdist.linux-x86_64/egg/keras/callbacks.py", line 39, in on_epoch_end
  File "build/bdist.linux-x86_64/egg/keras/callbacks.py", line 258, in on_epoch_end
ValueError: too many values to unpack
```

**Comment by pengpaiSH** [comment]
@fchollet Still waiting for your help : )

**Comment by fchollet** [comment]
This is fixed now, sorry about that.

**Comment by pengpaiSH** [comment]
@fchollet  Shall I just git pull keras and python setup.py install again ?

**Comment by fchollet** [comment]
Yes, that's it.

**Comment by pengpaiSH** [comment]
@fchollet Yes, it works right now. Look at this picture, what if I only care the `loss` and `val_loss` or `acc` and `valid_acc`? You know, the size actually is a noise and makes the `acc` and `valid_acc` not clear (should be in range 0 and 1). In other words, can I just turn the `size` off?
![image](https://cloud.githubusercontent.com/assets/3724085/9025312/707d2004-3932-11e5-997a-7dec0e00b2e3.png)

**Comment by fchollet** [comment]
Turn accuracy off (`show_accuracy=False` in Keras) to only visualize losses (which have the same scale).

If you want different graphs (at different scales) for losses and accuracies, you will have to modify the source of Hualos. I'd encourage you to do it.

Also you will need to modify the source to remove the values you don't need: size, batch...

**Comment by pengpaiSH** [comment]
@fchollet Thank you for you patience, always! Would you please give me more details about how to modify the source code in hualos to remove the size and batch, i.e. which file? It seems that I get confused with the `api.py` ...

**Comment by fchollet** [comment]
Just the javascript in this file: https://github.com/fchollet/hualos/blob/master/templates/test.html

Simply filter out the keys you won't want to display.
